import { useEffect,useState } from "react";
import { Link,useNavigate } from "react-router-dom";

function AdminDashboard(){
 const navigate=useNavigate();const[users,setUsers]=useState([]);const[internships,setInternships]=useState([]);const[applications,setApplications]=useState([]);const[certCount,setCertCount]=useState(0);const[loading,setLoading]=useState(true);
 useEffect(()=>{let session;try{session=JSON.parse(sessionStorage.getItem("user")||"null")}catch{sessionStorage.removeItem("user")}if(!session){navigate("/login");return}if(session.role!=="admin"){navigate("/login");return}(async()=>{try{const auth={headers:{Authorization:`Bearer ${session.token||""}`}};const[ur,ir]=await Promise.all([fetch("http://127.0.0.1:8000/api/users",auth),fetch("http://127.0.0.1:8000/api/internships")]);const people=ur.ok?await ur.json():[];const placements=ir.ok?await ir.json():[];setUsers(people);setInternships(placements);const [appLists,certLists]=await Promise.all([Promise.all(placements.map(async(item)=>{try{const r=await fetch(`http://127.0.0.1:8000/api/applications/internship/${item.id}`);return r.ok?await r.json():[]}catch{return []}})),Promise.all(people.filter((item)=>item.role==="student").map(async(item)=>{try{const r=await fetch(`http://127.0.0.1:8000/api/certificates/student/${item.id}`);return r.ok?await r.json():[]}catch{return []}}))]);setApplications(appLists.flat());setCertCount(certLists.flat().length)}catch(error){console.error("Admin dashboard error:",error)}finally{setLoading(false)}})()},[navigate]);
 if(loading)return <div className="page-loading"><div className="spinner-border text-primary"/><span>Loading platform overview…</span></div>;
 const countRole=(role)=>users.filter((item)=>item.role===role).length;const accepted=applications.filter((item)=>item.status==="accepted").length;const pending=applications.filter((item)=>item.status==="pending").length;const rejected=applications.filter((item)=>item.status==="rejected").length;const active=internships.filter((item)=>item.status==="active").length;
 return <div className="dashboard-page"><div className="page-heading-row"><div><span className="section-eyebrow">PLATFORM ADMINISTRATION</span><h1 className="mt-2">Platform overview</h1><p className="text-muted mb-0">A live view of InternProof users, opportunities, and verified outcomes.</p></div><Link to="/admin/reports" className="btn btn-primary">Platform reports <span className="ms-2">↗</span></Link></div>
 <div className="row g-3 mt-2">{[["Total users",users.length,"Across all roles","/admin/users"],["Students",countRole("student"),"Student accounts","/admin/users"],["Companies",countRole("company"),"Company accounts","/admin/companies"],["Colleges",countRole("college"),"College accounts","/admin/colleges"],["Internships",internships.length,`${active} active`,"/admin/internships"],["Applications",applications.length,`${accepted} accepted`,"/admin/reports"],["Certificates",certCount,"Issued records","/admin/certificates"]].map(([label,value,note,to])=><div className="col-6 col-xl-3" key={label}><Link to={to} className="metric-card"><span>{label}</span><strong>{value}</strong><small>{note}</small><i>↗</i></Link></div>)}</div>
 <div className="row g-3 mt-1"><div className="col-lg-7"><section className="panel-card"><div className="panel-heading"><div><span className="section-eyebrow">ACCOUNT DIRECTORY</span><h2>Recently added accounts</h2></div><Link to="/admin/users">Manage users ↗</Link></div>{users.length?users.slice(-6).reverse().map((person)=><div className="activity-row" key={person.id}><span className="activity-symbol">{(person.full_name||"U").slice(0,1).toUpperCase()}</span><span className="activity-copy"><b>{person.full_name||`User #${person.id}`}</b><small>{person.email}</small></span><span className="status-pill">{person.role}</span></div>):<div className="empty-inline"><span>No user records are available.</span></div>}</section></div><div className="col-lg-5"><section className="panel-card"><div className="panel-heading"><div><span className="section-eyebrow">APPLICATIONS</span><h2>Application outcomes</h2></div><Link to="/admin/reports">Reports ↗</Link></div>{[["Accepted",accepted,"accepted"],["Pending",pending,"pending"],["Rejected",rejected,"rejected"]].map(([label,value,status])=><div className="outcome-row" key={label}><span>{label}</span><div className="progress track-progress"><div className={`progress-bar outcome-${status}`} style={{width:`${applications.length?Math.round(value/applications.length*100):0}%`}}/></div><b>{value}</b></div>)}<div className="quick-links mt-3"><Link to="/admin/verification"><span>Verification center</span><small>Review evidence and certificate records</small><b>↗</b></Link><Link to="/admin/certificates"><span>Certificate directory</span><small>{certCount} issued certificates</small><b>↗</b></Link></div></section></div></div>
 <div className="row g-3 mt-1"><div className="col-12"><section className="panel-card"><div className="panel-heading"><div><span className="section-eyebrow">OPPORTUNITY DIRECTORY</span><h2>Latest internships</h2></div><Link to="/admin/internships">Manage internships ↗</Link></div>{internships.length?internships.slice(-5).reverse().map((item)=><div className="opportunity-row" key={item.id}><div><b>{item.title}</b><small>{item.company_name||"Company"} · {item.location||"Location not listed"}</small></div><span className={`status-pill status-${item.status||"active"}`}>{item.status||"active"}</span></div>):<div className="empty-inline"><span>No internship records are available.</span></div>}</section></div></div>
 </div>
}
export default AdminDashboard;
