import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";

function CompanyDashboard() {
  const navigate = useNavigate();
  const [user,setUser]=useState(null);const [internships,setInternships]=useState([]);const [applications,setApplications]=useState([]);const [loading,setLoading]=useState(true);
  useEffect(()=>{let stored;try{stored=JSON.parse(sessionStorage.getItem("user")||"null")}catch{sessionStorage.removeItem("user")}if(!stored){navigate("/login");return}if(stored.role!=="company"){navigate("/login");return}setUser(stored);(async()=>{try{const me=await fetch("http://127.0.0.1:8000/api/auth/me",{headers:{Authorization:`Bearer ${stored.token||""}`}});if(me.ok){stored={...stored,...await me.json()};sessionStorage.setItem("user",JSON.stringify(stored));setUser(stored)}const response=await fetch("http://127.0.0.1:8000/api/internships");if(!response.ok)throw new Error("Unable to load internships");const all=await response.json();const own=all.filter((item)=>Number(item.created_by)===Number(stored.user_id));setInternships(own);const lists=await Promise.all(own.map(async(item)=>{try{const result=await fetch(`http://127.0.0.1:8000/api/applications/internship/${item.id}`);return result.ok?await result.json():[]}catch{return []}}));setApplications(lists.flat())}catch(error){console.error("Company dashboard error:",error)}finally{setLoading(false)}})()},[navigate]);
  const accepted=applications.filter((item)=>item.status==="accepted").length;const pending=applications.filter((item)=>item.status==="pending").length;const active=internships.filter((item)=>item.status==="active").length;
  if(loading)return <div className="page-loading"><div className="spinner-border text-primary"/><span>Loading company workspaceâ€¦</span></div>;
  return <div className="dashboard-page"><div className="page-heading-row"><div><span className="section-eyebrow">COMPANY WORKSPACE</span><h1 className="mt-2">Good to see you, {user?.full_name?.split(" ")[0]||"there"}.</h1><p className="text-muted mb-0">Manage opportunities and support your next generation of talent.</p></div><Link to="/company/internships/create" className="btn btn-primary">Post an internship <span className="ms-2">ï¼‹</span></Link></div>
    <div className={`alert ${user?.company_verification_status === "verified" ? "alert-success" : user?.company_verification_status === "rejected" ? "alert-danger" : "alert-warning"} mt-3`}><strong>Company verification: {user?.company_verification_status || "pending"}</strong>{user?.company_verification_status !== "verified" && <div>Trusted actions such as posting internships, assigning tasks, reviewing evidence, and issuing certificates are restricted until an administrator verifies your account.</div>}</div>
    <div className="row g-3 mt-2">{[["Internships",internships.length,"Created by your team","/company/internships"],["Active listings",active,"Currently open","/company/internships"],["Applications",applications.length,"Across all listings","/company/applications"],["Accepted students",accepted,"Ready to get started","/company/students"]].map(([label,value,note,to])=><div className="col-6 col-xl-3" key={label}><Link to={to} className="metric-card"><span>{label}</span><strong>{value}</strong><small>{note}</small><i>â†—</i></Link></div>)}</div>
    <div className="row g-3 mt-1"><div className="col-lg-7"><section className="panel-card"><div className="panel-heading"><div><span className="section-eyebrow">INCOMING TALENT</span><h2>Recent applications</h2></div><Link to="/company/applications">Review all â†—</Link></div>{applications.length?applications.slice(0,6).map((application)=>{const internship=internships.find((item)=>item.id===application.internship_id);return <div className="activity-row" key={application.id}><span className="activity-symbol">{String(application.student_id||"S").slice(-2)}</span><span className="activity-copy"><b>Student #{application.student_id}</b><small>{internship?.title||`Internship #${application.internship_id}`}</small></span><span className={`status-pill status-${application.status||"pending"}`}>{application.status||"pending"}</span></div>}):<div className="empty-inline"><b>No applications yet</b><span>Applications will appear here when students apply to your internships.</span><Link to="/company/internships/create" className="btn btn-outline-primary btn-sm">Create a listing</Link></div>}</section></div><div className="col-lg-5"><section className="panel-card h-100"><div className="panel-heading"><div><span className="section-eyebrow">YOUR OPPORTUNITIES</span><h2>Active internships</h2></div><Link to="/company/internships">View all â†—</Link></div>{internships.length?internships.slice(0,5).map((item)=><div className="opportunity-row" key={item.id}><div><b>{item.title}</b><small>{item.location||"Location not listed"} Â· {item.status||"Active"}</small></div><Link to="/company/internships" aria-label={`View ${item.title}`}>â†—</Link></div>):<div className="empty-inline"><span>You haven't posted an internship yet.</span><Link to="/company/internships/create" className="btn btn-primary btn-sm">Post an internship</Link></div>}<div className="quick-links mt-3"><Link to="/company/tasks"><span>Assign student tasks</span><small>Keep accepted students on track</small><b>â†—</b></Link><Link to="/company/messages"><span>Open messages</span><small>Stay connected with students</small><b>â†—</b></Link></div></section></div></div>
    <div className="row g-3 mt-1"><div className="col-lg-12"><section className="panel-card"><div className="panel-heading"><div><span className="section-eyebrow">NEEDS ATTENTION</span><h2>Application queue</h2></div><span className="status-pill status-pending">{pending} pending</span></div>{pending===0?<div className="empty-inline"><span>You're all caught up on pending applications.</span></div>:<p className="small text-muted mb-0">Review pending applications to help students move forward.</p>}</section></div></div>
  </div>;
}
export default CompanyDashboard;

